[package]
name = "obs-service-elixir_mix_deps"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
thiserror = "2.0.9"
anyhow = "1.0.97"
flate2 = "1.1.0"
tar = "0.4.44"
zstd = "0.13.3"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
